# python translate.py -model ../models/global_general_inputfeed_filtervalidlen_vocabfixed/wmt14_model_global_general_inputfeed_filtervalidlen_vocabfixed_acc_62.51_ppl_5.83_e12.pt -src ../data/wmt14/newstest2014_reversed.en -tgt ../data/wmt14/newstest2014.de -verbose -output wmt14.test.pred.atok.global_general_inputfeed_filtervalidlen_vocabfixed_test_attn-test -beam_size 12 -gpu 0 -attn_debug > ../translation_logs/global_general_inputfeed_filtervalidlen_vocabfixed_beam12_attn-test

#python translate.py -model ../models/local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse/wmt14_model_local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse_acc_61.55_ppl_6.20_e12.pt -src ../data/wmt14/newstest2014_reversed.en -tgt ../data/wmt14/newstest2014.de -verbose -output wmt14.test.pred.atok.local-p_general_inputfeed_filtervalidlen_vocabfixed_unk-rpl_attn-test -beam_size 12 -gpu 0 -replace_unk -attn_debug > ../translation_logs/local-p_general_inputfeed_filtervalidlen_vocabfixed_unk-rpl_beam12_attn-test

#python translate.py -model ../models/global_general_inputfeed_filtervalidlen_vocabfixed/wmt14_model_global_general_inputfeed_filtervalidlen_vocabfixed_acc_62.51_ppl_5.83_e12.pt -src ../data/wmt14/newstest2014_reversed.en -tgt ../data/wmt14/newstest2014.de -verbose -output wmt14.test.pred.atok.global_general_inputfeed_filtervalidlen_vocabfixed_unk-rpl_attn-test -beam_size 12 -gpu 0 -replace_unk -attn_debug > ../translation_logs/global_general_inputfeed_filtervalidlen_vocabfixed_unk-rpl_beam12_attn-test

#python translate.py -model ../models/local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse_retrain/wmt14_model_local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse_retrain_acc_60.46_ppl_6.68_e12.pt -src ../data/wmt14/newstest2014_reversed.en -tgt ../data/wmt14/newstest2014.de -verbose -output wmt14.test.pred.atok.local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse_retrain_beam12 -beam_size 12 -gpu 0 -attn_debug > ../translation_logs/local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse_retrain_beam12_attn

# python translate.py -model ../models/local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse_retrain/wmt14_model_local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse_retrain_acc_60.46_ppl_6.68_e12.pt -src ../data/wmt14/newstest2014_reversed.en -tgt ../data/wmt14/newstest2014.de -verbose -output wmt14.test.pred.atok.local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse_retrain_unk-rpl_beam12 -beam_size 12 -gpu 0 -replace_unk -attn_debug > ../translation_logs/local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_fixreverse_retrain_unk-rpl_beam12_attn

# translate local-p general ceil p_t e4
# python translate.py -model ../models/local-p_general_inputfeed_filtervalidlen_vocabfixed_ceilpt/wmt14_model_local-p_general_inputfeed_filtervalidlen_vocabfixed_ceilpt_acc_55.32_ppl_9.10_e4.pt -src ../data/wmt14/newstest2014_reversed.en -tgt ../data/wmt14/newstest2014.de -verbose -output wmt14.test.pred.atok.local-p_general_inputfeed_filtervalidlen_vocabfixed_ceilpt_beam12_e4 -beam_size 12 -gpu 0 -attn_debug > ../translation_logs/local-p_general_inputfeed_filtervalidlen_vocabfixed_ceilpt_beam12_attn_e4

# translate global general e4
# python translate.py -model ../models/global_general_inputfeed_filtervalidlen_vocabfixed/wmt14_model_global_general_inputfeed_filtervalidlen_vocabfixed_acc_59.43_ppl_7.07_e4.pt -src ../data/wmt14/newstest2014_reversed.en -tgt ../data/wmt14/newstest2014.de -verbose -output wmt14.test.pred.atok.global_general_inputfeed_filtervalidlen_vocabfixed_attn_beam12_e4 -beam_size 12 -gpu 0 -attn_debug > ../translation_logs/global_general_inputfeed_filtervalidlen_vocabfixed_beam12_attn_e4

# translate local-p general v4 e5
python translate.py -model ../models/local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_reverse-src_4/wmt14_model_local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_reverse-src_4_acc_55.11_ppl_8.85_e5.pt -src ../data/wmt14/newstest2014_reversed.en -tgt ../data/wmt14/newstest2014.de -verbose -output wmt14.test.pred.atok.local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_reverse-src_4_attn_beam12_e5 -beam_size 12 -gpu 0 -attn_debug > ../translation_logs/local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_reverse-src_4_beam12_attn_e5

# translate local-p general v3 e4
#python translate.py -model ../models/local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_reverse-src_3/wmt14_model_local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_reverse-src_3_acc_56.35_ppl_8.59_e4.pt -src ../data/wmt14/newstest2014_reversed.en -tgt ../data/wmt14/newstest2014.de -verbose -output wmt14.test.pred.atok.local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_reverse-src_3_attn_beam12_e4 -beam_size 12 -gpu 0 -attn_debug > ../translation_logs/local-p_general_inputfeed_filtervalidlen_vocabfixed_floorpt_reverse-src_3_beam12_attn_e4
